### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'subm'

### ISSUE THREAD

**Issue by daihong980826** [Poley97/FSTR#9]

**Comment by daihong980826** [comment]
您好，我在运行以下命令时，遇到如下报错，请问可能是什么问题呢？期待您的回复！
【命令】
bash tools/dist_train.sh projects/configs/lidar/fstr_xlarge_voxel0050_cbgs_20e.py 1
【报错】
2024-09-24 03:59:40,578 - mmdet - INFO - Set random seed to 0, deterministic: False
Traceback (most recent call last):
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/data/wdh/FSTR/projects/mmdet3d_plugin/models/dense_heads/fstr_head.py", line 330, in __init__
    self.sparse_maxpool_2d = spconv.SparseMaxPool2d(3, 1, 1, subm=True, algo=ConvAlgo.Native, indice_key='max_pool_head_3')
TypeError: __init__() got an unexpected keyword argument 'subm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/data/wdh/FSTR/projects/mmdet3d_plugin/models/detectors/fstr.py", line 25, in __init__
    super(FSTRDetector, self).__init__(**kwargs)
  File "/data/wdh/FSTR/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 62, in __init__
    self.pts_bbox_head = builder.build_head(pts_bbox_head)
  File "/data/wdh/FSTR/mmdetection3d/mmdet3d/models/builder.py", line 68, in build_head
    return MMDET_HEADS.build(cfg)
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FSTRHead: __init__() got an unexpected keyword argument 'subm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 293, in <module>
    main()
  File "tools/train.py", line 249, in main
    model = build_model(
  File "/data/wdh/FSTR/mmdetection3d/mmdet3d/models/builder.py", line 122, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/data/wdh/FSTR/mmdetection3d/mmdet3d/models/builder.py", line 95, in build_detector
    return MMDET_DETECTORS.build(
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/fstr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FSTRDetector: FSTRHead: __init__() got an unexpected keyword argument 'subm'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1404727) of binary: /opt/conda/envs/fstr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed

**Comment by harborsarah** [comment]
Hi, did you solve the problem? I met the same problem when running the code.
